version: '3'

services:
  postgres:
    image: postgres:9.5.20
    restart: always

  redis:
    image: redis:latest
    restart: always

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4000:80'

  api:
    restart: always
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

  client:
    restart: always
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    build:
      context: ./client
      dockerfile: Dockerfile.dev

  worker:
    restart: always
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
